### PR TITLE
Initial refactor of HTML to Nunjuks templates

### PR DESCRIPTION
**Pull request by ShawhurstDigital**
Initial refactor passed local manual test.
Refactoring comprised the following;

1. Moving all .html files to .njk
2. Creating layouts and partials in _includes directory

This is just a small step in the right direction.
Further refinements are expected.
For example, 11ty filters should overcome the dynamic links to CSS files in page head issue.

### CODE REVIEW

**Comment by monkeywhovapes** [comment]
This is awesome! I only recently started using 11ty and really see the benefits of it on top of the WebKit from oak harbor.

**Comment by ShawhurstDigital** [comment]
Hey

Thanks, that's very kind of you but I can't take any credit. All the awesomeness is down to the toolchain and Oak Harbor's starter.

I probably know less than you do at this point, so take what you see with a large dose of salt!

27 Oct 2022 13:02:53 monkeywhovapes ***@***.***>:

**Comment by monkeywhovapes** [comment]
I see that you're still working on the refactoring of the webpages?

I have a couple of questions... How does the page know which is the "active" page... meaning if I were on the portfolio page, how can I make the menu for "Portfolio" active? 

The same question goes for the header with the meta-keywords section, how can this be unique for each page if there's one header file?

Finally, are you putting together a blog "ability"? I was working on this earlier today off of your setup. 

All in all, this is still a great improvement over the original kit. In fact, I was kinda playing with tailwindcss and it has sped up some testing / mocking.

**Comment by ShawhurstDigital** [comment]
I'm still working on all of it when I get time.

I am aware of the first two issues you raised, the active page and keywords, but it's not killing the build and it's more than just a minor tweak like a typo. I'll take a pull request if you want to submit something after reading the next couple of paras. 

The 11ty docs cover the aria-current attribute [here](https://www.11ty.dev/docs/pagination/nav/#starter-example).

As for keywords, rather than me explain it poorly, read through these sections in the docs and it should be apparent. If it doesn't make sense, you'll see when I get there. 

[Layouts](https://www.11ty.dev/docs/templates/)
[Data](https://www.11ty.dev/docs/data/)

Again, I'd take a pull request if you come up with something but it's not breaking anything at this point.

I've started Netlification with CMS. I'd love to see your implementation, or take a pull.

I've not used Tailwind yet but I use Bootstrap sometimes. And yes, it's fine for prototyping api endpoints for example when just a wee bit of style stops your eyes from bleeding. There are a few starter projects using Tailwind/Bootstrap if you check the docs, [11tyrocks](https://11ty.rocks/) and here on GitHub.

**Pull request merged**
